# Generated by Django 4.2 on 2024-11-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_transaction_gift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
