# Generated by Django 4.2 on 2024-11-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='day',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
