# Generated by Django 4.2 on 2024-12-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
