# Generated by Django 4.2 on 2024-11-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createfamily',
            name='family_notification',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='createfamily',
            name='join_mode',
            field=models.CharField(choices=[('leader/co-leader review', 'Leader/Co-Leader Review'), ('join_freely', 'Join Freely')], default='1', max_length=54),
        ),
    ]
