# Generated by Django 4.2 on 2024-11-24 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hapi_app', '0022_country_county_flag'),
        ('family', '0002_createfamily_family_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createfamily',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_family', to='hapi_app.userlv'),
        ),
    ]
