# Generated by Django 4.2 on 2024-11-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_createfamily_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='is_top_contributor',
        ),
        migrations.RemoveField(
            model_name='weeklyranking',
            name='total_coins',
        ),
        migrations.AlterField(
            model_name='createfamily',
            name='join_mode',
            field=models.CharField(choices=[('leader/co-leader review', 'Leader/Co-Leader Review'), ('join_freely', 'Join Freely')], default='leader/co-leader review', max_length=54),
        ),
    ]
