# Generated by Django 4.2 on 2024-11-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_remove_familymember_is_top_contributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='is_join',
            field=models.BooleanField(default=False),
        ),
    ]
