# Generated by Django 4.2 on 2024-11-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_familymember_is_join'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createfamily',
            old_name='total_coins',
            new_name='bonus_level',
        ),
        migrations.AddField(
            model_name='createfamily',
            name='contribution',
            field=models.BigIntegerField(default=0),
        ),
    ]
