# Generated by Django 4.2 on 2024-11-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_rename_total_coins_createfamily_bonus_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='contribution',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familymember',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymember',
            name='reward',
            field=models.BigIntegerField(default=0),
        ),
    ]
