# Generated by Django 4.2 on 2024-11-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0007_familymember_contribution_familymember_is_leader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True)),
                ('target_contribution', models.BigIntegerField()),
                ('leader_coins', models.BigIntegerField()),
                ('top1_coins', models.BigIntegerField()),
                ('top2_coins', models.BigIntegerField()),
                ('top3_coins', models.BigIntegerField()),
            ],
        ),
    ]
