# Generated by Django 4.2 on 2024-12-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0008_bonuslevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='createfamily',
            name='family_image',
            field=models.ImageField(blank=True, null=True, upload_to='family_image/'),
        ),
    ]
