# Generated by Django 4.2 on 2024-12-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0009_createfamily_family_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createfamily',
            name='join_mode',
            field=models.CharField(choices=[('Leader/Co-Leader Review', 'Leader/Co-Leader Review'), ('Join Freely', 'Join Freely')], default='leader/co-leader review', max_length=54),
        ),
    ]
