# Generated by Django 4.2 on 2024-11-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hapi_app', '0003_follower'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=set(),
        ),
    ]
