# Generated by Django 4.2 on 2024-11-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hapi_app', '0004_alter_follower_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
