# Generated by Django 4.2 on 2024-11-18 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hapi_app', '0009_rename_followeruser_follower_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_visit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
