# Generated by Django 4.2 on 2024-11-18 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hapi_app', '0011_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='invitee',
        ),
        migrations.AddField(
            model_name='invitation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(check=models.Q(('email__isnull', False), ('phone__isnull', False), _connector='OR'), name='email_or_phone_must_be_present'),
        ),
    ]
