# Generated by Django 4.2 on 2024-11-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapi_app', '0012_remove_invitation_accepted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='wallet',
            name='diamond_coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='gold_coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
