# Generated by Django 4.2 on 2024-11-19 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hapi_app', '0014_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
    ]
