# Generated by Django 4.2 on 2024-11-23 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hapi_app', '0016_walletlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletlog',
            old_name='user',
            new_name='user_id',
        ),
    ]
