# Generated by Django 4.2 on 2024-11-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hapi_app', '0017_rename_user_walletlog_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletlog',
            old_name='user_id',
            new_name='user',
        ),
    ]
