# Generated by Django 4.2 on 2024-11-24 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hapi_app', '0018_rename_user_id_walletlog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_svip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lv', to='hapi_app.userlv'),
            preserve_default=False,
        ),
    ]
