# Generated by Django 4.2 on 2024-11-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapi_app', '0020_country_rename_level_userlv_level_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=54, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='short_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userlv',
            name='level_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
