# Generated by Django 4.2 on 2024-11-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapi_app', '0021_alter_country_name_alter_country_short_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='county_flag',
            field=models.ImageField(blank=True, null=True, upload_to='county_flag/'),
        ),
    ]
