# Generated by Django 4.2 on 2024-11-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapi_app', '0022_country_county_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=54, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
