# Generated by Django 4.2 on 2024-11-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapi_app', '0023_user_birth_day_user_fcm_token_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
