# Generated by Django 4.2 on 2024-12-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapi_app', '0026_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token_google',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('google', 'google'), ('facebook', 'facebook')], max_length=54, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
