# Generated by Django 4.2 on 2024-12-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapi_app', '0027_user_access_token_google_user_auth_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_route',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
