# Generated by Django 4.2 on 2024-12-15 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hapi_app', '0028_notification_notification_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='family',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
