# Generated by Django 4.2 on 2024-12-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hapi_app', '0029_notification_family_notification_user2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='family',
            new_name='family_image',
        ),
    ]
