# Generated by Django 4.2 on 2024-11-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='impression',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='impression',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='Advertiser',
        ),
        migrations.DeleteModel(
            name='Impression',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
