# Generated by Django 4.2 on 2024-11-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_p', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couplerelationship',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
