# Generated by Django 4.2 on 2024-11-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_p', '0002_alter_couplerelationship_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='couplerelationship',
            name='level_up',
            field=models.BooleanField(default=False),
        ),
    ]
