# Generated by Django 4.2 on 2024-12-01 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal_image', models.ImageField(blank=True, null=True, upload_to='medal_image/')),
                ('medal_name', models.CharField(max_length=50)),
                ('medal_type', models.CharField(blank=True, choices=[('Achievement', 'Achievement'), ('Gift', 'Gift'), ('Activity', 'Activity')], max_length=54, null=True)),
                ('medal_star', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMedal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal_send_count', models.PositiveIntegerField(default=0)),
                ('is_show', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medal', to='medal.medalinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_medal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
