# Generated by Django 4.2 on 2024-12-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedal',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
