# Generated by Django 4.2 on 2024-12-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medal', '0002_alter_usermedal_is_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermedal',
            old_name='medal_send_count',
            new_name='send_count',
        ),
        migrations.AddField(
            model_name='medalinfo',
            name='medal_send_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
