# Generated by Django 4.2 on 2024-12-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medal', '0003_rename_medal_send_count_usermedal_send_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medalinfo',
            name='medal_send_count',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
