# Generated by Django 4.2 on 2024-12-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargecoin',
            name='total_coins',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
